### ISSUE TITLE
Can't seem to get ttty working for website

### ISSUE THREAD

**Issue by iJustinCabral** [mkrl/ttty#32]
**Using React JS**

Trying to install ttty for a react website I'm trying to set up. I'm not quite sure on how to go about setting it based on the instructions. My setup inside the .js page looks like this:

![issue1](https://user-images.githubusercontent.com/1973054/176056535-d727345c-28b5-4e4a-9208-f3f5609b24d4.png)

However, when compiling I seem to be getting a bunch of errors. Am I setting this up correctly? 

Any help would be appreciated, thank you.

**Comment by mkrl** [comment]
Can you share some details? What are you using to build the app / what are the errors you're facing?

**Comment by mkrl** [comment]
By the looks of your code, you might have forgotten to pass "commands" to `initTerminal`. This is a required parameter.
You also might want to wrap it into `useEffect` since you only need to init the terminal once.

Here's a working example https://codesandbox.io/s/thirsty-austin-d49unh?file=/src/App.js

**Comment by iJustinCabral** [comment]
Working great now. We weren't wrapping it inside of useEffect correctly. Thanks you!
